# Nome da Ação do GitHub
name: Generate Snake

# Define quando a ação deve rodar
on:
  # Roda a cada 6 hours automaticamente
  schedule:
    - cron: "0 */6 * * *"
  # Permite que você rode a ação manualmente pela aba "Actions" do seu repositório
  workflow_dispatch:

# Define o trabalho que será executado
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pega o código do seu repositório para poder fazer alterações
      - uses: actions/checkout@v2

      # Roda a ação que gera a animação da cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          # Seu nome de usuário do GitHub (já está correto)
          github_user_name: opgmoraes
          
          # Define os nomes dos arquivos que serão gerados
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Faz o "push" (envio) dos arquivos gerados de volta para o seu repositório
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica os arquivos gerados em uma branch separada chamada "output"
      # É desta branch que a imagem no seu README é lida
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
